-- Migrasi v3: Katalog Terpusat OriginPlayer (Movie, Series, Episodes & Multi-Server Streams)
-- Jalankan di SQL Editor Supabase untuk merombak dari playlist lama menjadi katalog terpusat.

-- 1. Tabel Konten Utama (Movie / Series)
create table if not exists op_titles (
  id bigint generated by default as identity primary key,
  tmdb_id integer unique not null,
  type text not null check (type in ('movie', 'series')),
  title text not null,
  slug text not null,
  poster text,
  backdrop text,
  synopsis text,
  year integer,
  rating numeric(3,1),
  genres text[],
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index untuk pencarian cepat
create index if not exists idx_op_titles_type on op_titles(type);
create index if not exists idx_op_titles_tmdb_id on op_titles(tmdb_id);

-- 2. Tabel Episode (Khusus TV Series)
create table if not exists op_episodes (
  id bigint generated by default as identity primary key,
  title_id bigint references op_titles(id) on delete cascade not null,
  season_number integer not null,
  episode_number integer not null,
  episode_title text,
  overview text,
  still_path text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (title_id, season_number, episode_number)
);

create index if not exists idx_op_episodes_title_season on op_episodes(title_id, season_number);

-- 3. Tabel Stream / Servers (Multi-fallback per Movie atau Episode)
create table if not exists op_streams (
  id bigint generated by default as identity primary key,
  title_id bigint references op_titles(id) on delete cascade,
  episode_id bigint references op_episodes(id) on delete cascade,
  server_name text not null default 'Abyss Utama',
  stream_url text not null,
  priority integer default 1,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS permissive agar admin app & visitor bisa query (atau disesuaikan)
alter table op_titles enable row level security;
alter table op_episodes enable row level security;
alter table op_streams enable row level security;

create policy "Public read op_titles" on op_titles for select using (true);
create policy "Public insert/update op_titles" on op_titles for all using (true);

create policy "Public read op_episodes" on op_episodes for select using (true);
create policy "Public insert/update op_episodes" on op_episodes for all using (true);

create policy "Public read op_streams" on op_streams for select using (true);
create policy "Public insert/update op_streams" on op_streams for all using (true);
